### ISSUE TITLE
Support https access

### ISSUE THREAD

**Issue by der** [epimorphics/rainfall-api-demonstrator#4]
The map and API accesses currently force http scheme as so the demonstrator doesn't work if accessed over https due to browser security restrictions.

**Comment by ijdickinson** [comment]
@der I believe this is now fixed, but I'm not sure I can remember how to do the deploy to test it in production!

**Comment by der** [comment]
Thanks @ijdickinson. I seem to remember it gets baked into the API app as part of the static documentation pages. I'll get it deployed.

**Comment by der** [comment]
Deploy and https problem is solved thanks.
