### ISSUE TITLE
Incorrect "latest reading" dates

### ISSUE THREAD

**Issue by der** [epimorphics/rainfall-api-demonstrator#5]
In deploying the https fix I noticed that the "latest reading" value (and the right hand limit of the graph axis) is often out by a few days. Seems this was true before and unrelated to https fix.

For example, currently station 43103 (on Salisbury plain) is showing in the app as last reading 30 Mar 2017 16:00 whereas if you follow the links to the API for the latest 100 readings it was at 2017-04-03T04:00:00Z.

Wonder if there might be only 0mm readings between 30th and now? Or whether there's an API count limit being hit (in which case should raise it)?

**Comment by ijdickinson** [comment]
We've identified the problem (missing `_sorted` parameter), and Mike is going to add it to his list to do today.

**Comment by paperclipmonkey** [comment]
Fixed in 1ada07e
